
Implement a Retrieval-Augmented Generation (RAG) system for robotics documentation. This includes generating 10-15 synthetic robotics documents, setting up an embedding model and a vector store, chunking and embedding the documents, implementing a retrieval and response generation function, and demonstrating the system with example queries. Finally, provide a markdown explanation of the RAG architecture.

##Synthetic Robotics Documentation


10-15 synthetic documents covering object handling instructions, safety protocols, equipment specifications, and troubleshooting guides for a hypothetical robot. These documents will be saved as text files for the knowledge base.


### Hypothetical Robot: 'OmniBot 7000' (OB-7000)

The OmniBot 7000 is an advanced industrial collaborative robot designed for precision manufacturing, assembly, and logistics in various environments, including human-robot co-working spaces. It features a multi-axis arm, an interchangeable end-effector system (e.g., grippers, welding torches, vision systems), and a mobile base for increased flexibility.

### Document Topics:

1.  **Object Handling Instructions:**
    *   `OB7000_Gripper_Operation_Manual.txt`
    *   `OB7000_Vision_System_Calibration.txt`
    *   `OB7000_Payload_Limits_Guide.txt`
2.  **Safety Protocols:**
    *   `OB7000_Emergency_Stop_Procedure.txt`
    *   `OB7000_Human_Robot_Collaboration_Safety.txt`
    *   `OB7000_Maintenance_Safety_Lockout.txt`
3.  **Equipment Specifications:**
    *   `OB7000_Technical_Specifications.txt`
    *   `OB7000_End_Effector_Compatibility.txt`
    *   `OB7000_Power_Requirements_Guide.txt`
4.  **Troubleshooting Guides:**
    *   `OB7000_Error_Code_Reference.txt`
    *   `OB7000_Communication_Troubleshooting.txt`
    *   `OB7000_Arm_Stall_Troubleshooting.txt`
    *   `OB7000_Software_Update_Failure_Recovery.txt`

**Reasoning**:
Now that the hypothetical robot and document topics are defined, I will generate the content for each document and save them as separate text files as per the instructions.



In [1]:
import os

def generate_document_content(filename):
    if 'Gripper_Operation_Manual' in filename:
        return """# OB-7000 Gripper Operation Manual\n\n## 1. Introduction\nThe OB-7000's standard gripper is a dual-finger parallel type, designed for robust and precise object handling.\n\n## 2. Operation Modes\n*   **Force-Controlled Mode:** Ideal for delicate objects, maintaining a constant grip force.\n*   **Position-Controlled Mode:** Best for rigid objects where specific grip width is required.\n\n## 3. Calibration\nPerform gripper calibration weekly or after any mechanical adjustment. Refer to Section 4.5 of the main manual.\n\n## 4. Maintenance\nInspect gripper pads daily for wear and tear. Replace if damage is observed. Lubricate moving parts quarterly.\n\n## 5. Specifications\n*   Max Grip Force: 150 N\n*   Max Opening: 120 mm\n*   Repeatability: +/- 0.02 mm\n\n---END OF DOCUMENT---"""
    elif 'Vision_System_Calibration' in filename:
        return """# OB-7000 Vision System Calibration Guide\n\n## 1. Overview\nThe integrated vision system (Model 'EyeBot 3000') provides precise object recognition and localization for the OB-7000.\n\n## 2. Calibration Procedure\n1.  **Preparation:** Ensure the calibration target is clean and free of obstructions. Place the target within the robot's workspace.\n2.  **Software Initiation:** Access the 'Vision Calibration' module in the OB-7000 control software.\n3.  **Automatic Scan:** Select 'Start Automatic Calibration'. The robot will move to predefined positions to capture images of the target.\n4.  **Verification:** Upon completion, the software will display calibration accuracy. Recalibrate if accuracy is below 98%.\n\n## 3. Best Practices\n*   Calibrate in consistent lighting conditions.\n*   Avoid glare on the calibration target.\n\n---END OF DOCUMENT---"""
    elif 'Payload_Limits_Guide' in filename:
        return """# OB-7000 Payload Limits Guide\n\n## 1. Introduction\nUnderstanding the payload limits is critical for safe and efficient operation of the OmniBot 7000.\n\n## 2. Rated Payload\nThe maximum rated payload for the OB-7000 manipulator arm is 10 kg (22 lbs) at full extension.\n\n## 3. Dynamic Payload Reduction\n*   **High Speed Operations:** For speeds exceeding 75% of max speed, reduce payload by 20%.\n*   **Offset Loads:** Objects gripped with a significant offset from the tool center point (TCP) will reduce effective payload capacity. Consult the load diagram in Appendix B.\n\n## 4. End-Effector Weight\nThe weight of the end-effector (e.g., gripper, welding torch) must be included in the total payload calculation.\n\n---END OF DOCUMENT---"""
    elif 'Emergency_Stop_Procedure' in filename:
        return """# OB-7000 Emergency Stop Procedure\n\n## 1. Immediate Actions\nIn an emergency, immediately press any red 'EMERGENCY STOP' button located on the robot base, teach pendant, or control cabinet.\n\n## 2. System Status After E-Stop\n*   All robot motion will cease instantly.\n*   Power to motors will be cut, and brakes will engage.\n*   The system will enter a 'STOP 0' (uncontrolled stop) state.\n\n## 3. Restarting After E-Stop\n1.  **Clear Hazard:** Identify and resolve the cause of the emergency.\n2.  **Release E-Stop:** Twist the pressed E-Stop button clockwise to release it.\n3.  **Reset Safety System:** On the teach pendant, navigate to 'Safety Status' and select 'Reset'.\n4.  **Power On:** Initiate 'Power On' from the teach pendant or control panel.\n\n---END OF DOCUMENT---"""
    elif 'Human_Robot_Collaboration_Safety' in filename:
        return """# OB-7000 Human-Robot Collaboration (HRC) Safety Guidelines\n\n## 1. Introduction\nThe OB-7000 is designed for safe HRC, utilizing advanced sensors and safety functions.\n\n## 2. Safety Zones\n*   **Green Zone:** Safe for human entry, robot operates in reduced speed/force mode.\n*   **Yellow Zone:** Robot slows down upon human detection, prepares for full stop.\n*   **Red Zone:** Robot stops immediately upon human entry. Entry prohibited during normal operation.\n\n## 3. Collaborative Functions\n*   **Safe Stop (PFL):** Robot stops when human enters predefined safety zone.\n*   **Hand Guiding:** Allows operator to manually guide the robot arm for programming or precise positioning.\n*   **Speed & Separation Monitoring:** Dynamically adjusts robot speed based on human proximity.\n\n## 4. Training Requirement\nAll personnel working in HRC environments with the OB-7000 must complete certified HRC safety training.\n\n---END OF DOCUMENT---"""
    elif 'Maintenance_Safety_Lockout' in filename:
        return """# OB-7000 Maintenance Safety Lockout/Tagout (LOTO) Procedure\n\n## 1. Purpose\nTo ensure the robot is safely de-energized and unable to operate during maintenance or repair activities.\n\n## 2. LOTO Steps\n1.  **Preparation:** Notify all affected personnel of impending shutdown.\n2.  **Shutdown:** Place the robot in a safe, de-energized state. Press the E-Stop and power off the main controller.\n3.  **Isolation:** Disconnect all energy sources (electrical, pneumatic, hydraulic). For electrical, turn off the main circuit breaker.
4.  **Lockout/Tagout:** Apply personal lockout devices and tags to all energy isolation points.\n5.  **Verification:** Attempt to start the robot or operate controls to ensure it is de-energized. Confirm zero energy state.\n\n## 3. Restoring Operation\n1.  **Remove LOTO Devices:** Only the person who applied the lock can remove it.\n2.  **Re-energize:** Restore energy sources.\n3.  **Notify Personnel:** Inform affected personnel that maintenance is complete and robot is restarting.\n\n---END OF DOCUMENT---"""
    elif 'Technical_Specifications' in filename:
        return """# OB-7000 Technical Specifications\n\n## 1. General\n*   **Model:** OmniBot 7000 (OB-7000)\n*   **Type:** 6-Axis Collaborative Industrial Robot\n*   **Application:** Assembly, Pick & Place, Welding, Inspection\n\n## 2. Performance\n*   **Payload:** 10 kg (22 lbs)\n*   **Reach:** 1300 mm (51.2 inches)\n*   **Repeatability:** +/- 0.02 mm\n*   **Max Speed:** 2.5 m/s (TCP speed)\n\n## 3. Physical\n*   **Weight:** 60 kg (excluding controller)\n*   **Footprint:** 300 mm x 300 mm\n*   **Power Supply:** 200-240 VAC, 50/60 Hz, 1-Phase\n*   **Power Consumption:** 1 kW (typical), 2.5 kW (max)\n\n## 4. Environmental\n*   **Operating Temperature:** 0-45 °C (32-113 °F)\n*   **IP Rating:** IP54 (Arm), IP20 (Controller)\n\n---END OF DOCUMENT---"""
    elif 'End_Effector_Compatibility' in filename:
        return """# OB-7000 End-Effector Compatibility Guide\n\n## 1. Overview\nThe OB-7000 features a standardized tool flange for quick and easy end-effector changes.\n\n## 2. Compatible End-Effector Types\n*   **Standard Grippers:** Parallel, angular, vacuum grippers (e.g., Schunk, OnRobot, Robotiq).\n*   **Welding Torches:** MIG/MAG, TIG (requires specific adapter kit and communication interface).\n*   **Vision Systems:** EyeBot 3000 series, Cognex, Basler cameras.\n*   **Force/Torque Sensors:** ATI Industrial Automation, Robotiq FT 300.\n\n## 3. Electrical & Pneumatic Interfaces\nThe tool flange provides standard M8 connectors for electrical signals (24V DC, I/O) and 6mm pneumatic lines.\n\n## 4. Software Integration\nEnd-effectors require corresponding URCaps (Universal Robot software components) for seamless integration into the OB-7000 control software.\n\n---END OF DOCUMENT---"""
    elif 'Power_Requirements_Guide' in filename:
        return """# OB-7000 Power Requirements Guide\n\n## 1. Introduction\nProper power supply is essential for the reliable operation of the OB-7000.\n\n## 2. Main Power Input\n*   **Voltage:** 200-240 VAC, Single-Phase\n*   **Frequency:** 50/60 Hz\n*   **Current:** 10 Amps (dedicated circuit recommended)\n\n## 3. Peak Power Consumption\nWhile typical consumption is 1 kW, peak loads during rapid movements or heavy lifts can reach 2.5 kW. Ensure circuit can handle peak requirements.\n\n## 4. Grounding\nThe robot system and control cabinet MUST be properly grounded to prevent electrical shock and ensure EMI compliance.\n\n## 5. Auxiliary Power\n24V DC auxiliary power is available at the tool flange (max 1.5A) for end-effectors.\n\n---END OF DOCUMENT---"""
    elif 'Error_Code_Reference' in filename:
        return """# OB-7000 Error Code Reference Manual\n\n## 1. Introduction\nThis document lists common error codes, their meanings, and suggested troubleshooting steps.\n\n## 2. Common Error Codes\n*   **E101 - Joint Limit Exceeded:**\n    *   **Description:** Robot arm attempted to move beyond its physical joint limits.\n    *   **Action:** Check program path. Manually move robot within limits using freedrive. Reset error.\n*   **E105 - TCP Collision Detected:**\n    *   **Description:** Force sensor detected unexpected contact at the tool center point.\n    *   **Action:** Inspect work area for obstructions. Check payload and force settings. Reset error.\n*   **E203 - Communication Loss (Teach Pendant):**\n    *   **Description:** Connection between control box and teach pendant lost.\n    *   **Action:** Check teach pendant cable. Restart teach pendant. Restart control box if necessary.\n*   **E301 - Motor Overload:**\n    *   **Description:** One or more motors exceeded their thermal limits.\n    *   **Action:** Reduce payload or speed. Allow robot to cool down. Check for mechanical binding.\n\n---END OF DOCUMENT---"""
    elif 'Communication_Troubleshooting' in filename:
        return """# OB-7000 Communication Troubleshooting Guide\n\n## 1. Overview\nThis guide addresses common issues with network and device communication for the OB-7000.\n\n## 2. Network Connectivity (Ethernet)\n*   **Symptom:** Robot not reachable via network, no ping response.\n*   **Action:** Check Ethernet cable connections. Verify IP address settings in controller. Restart network switch/router.\n\n## 3. Teach Pendant Communication\n*   **Symptom:** Teach pendant displays 'Disconnected' or 'No Communication'.\n*   **Action:** Securely re-plug the teach pendant cable. Restart the teach pendant. If issue persists, try another teach pendant.\n\n## 4. End-Effector Communication\n*   **Symptom:** End-effector not responding, error message regarding tool communication.\n*   **Action:** Check end-effector's power and communication cables. Verify URCap is installed and enabled. Re-initialize the end-effector from the 'Installation' tab.\n\n---END OF DOCUMENT---"""
    elif 'Arm_Stall_Troubleshooting' in filename:
        return """# OB-7000 Arm Stall Troubleshooting Guide\n\n## 1. Introduction\nAn arm stall occurs when the robot's motion is unexpectedly impeded, leading to an error state.\n\n## 2. Symptoms\n*   Robot motion stops abruptly.\n*   Error message: 'E103 - Joint Stall Detected' or 'E105 - TCP Collision Detected'.\n*   Robot arm may be visibly obstructed.\n\n## 3. Troubleshooting Steps\n1.  **Inspect Workspace:** Carefully check the robot's path and surrounding area for physical obstructions (e.g., tools, debris, loose cables).\n2.  **Check Payload:** Ensure the current payload is within the robot's specified limits.\n3.  **Review Program:** Verify the robot's program path for singularities or unrealistic movements.\n4.  **Monitor Force Feedback:** If equipped, check force sensor readings for anomalies. Adjust sensitivity if too high.\n5.  **Mechanical Inspection:** Power off the robot (LOTO) and manually check joint freedom of movement. Look for binding or damage.\n\n---END OF DOCUMENT---"""
    elif 'Software_Update_Failure_Recovery' in filename:
        return """# OB-7000 Software Update Failure Recovery\n\n## 1. Introduction\nThis guide provides steps to recover from a failed software update on the OB-7000 controller.\n\n## 2. Symptoms of Failure\n*   Robot fails to boot after update attempt.\n*   Controller displays an error message related to software loading.\n*   System stuck in a boot loop.\n\n## 3. Recovery Procedure (USB Rollback)\n1.  **Prepare USB:** Obtain a USB drive with a previously working OB-7000 software version or a recovery image.\n2.  **Enter Recovery Mode:** Power off the robot controller. Insert the USB drive. Power on the controller while holding the 'Recovery' button (located inside the front panel).\n3.  **Select Rollback Option:** On the display, choose 'Rollback to Previous Version' or 'Install from USB'.\n4.  **Confirm & Restart:** Follow on-screen prompts to complete the installation. Once finished, remove USB and restart the controller.\n\n## 4. Preventative Measures\n*   Always back up robot programs and configurations before an update.\n*   Ensure stable power supply during the update process.\n\n---END OF DOCUMENT---"""
    else:
        return f"# Content for {filename.replace('.txt', '').replace('_', ' ')}\n\nThis is a placeholder document for {filename}. Specific instructions, specifications, or troubleshooting steps would be detailed here.\n\n---END OF DOCUMENT---"


document_filenames = [
    'OB7000_Gripper_Operation_Manual.txt',
    'OB7000_Vision_System_Calibration.txt',
    'OB7000_Payload_Limits_Guide.txt',
    'OB7000_Emergency_Stop_Procedure.txt',
    'OB7000_Human_Robot_Collaboration_Safety.txt',
    'OB7000_Maintenance_Safety_Lockout.txt',
    'OB7000_Technical_Specifications.txt',
    'OB7000_End_Effector_Compatibility.txt',
    'OB7000_Power_Requirements_Guide.txt',
    'OB7000_Error_Code_Reference.txt',
    'OB7000_Communication_Troubleshooting.txt',
    'OB7000_Arm_Stall_Troubleshooting.txt',
    'OB7000_Software_Update_Failure_Recovery.txt'
]

for filename in document_filenames:
    content = generate_document_content(filename)
    with open(filename, 'w') as f:
        f.write(content)
    print(f"Generated and saved: {filename}")

print("\nAll synthetic documents have been generated and saved.")

Generated and saved: OB7000_Gripper_Operation_Manual.txt
Generated and saved: OB7000_Vision_System_Calibration.txt
Generated and saved: OB7000_Payload_Limits_Guide.txt
Generated and saved: OB7000_Emergency_Stop_Procedure.txt
Generated and saved: OB7000_Human_Robot_Collaboration_Safety.txt
Generated and saved: OB7000_Maintenance_Safety_Lockout.txt
Generated and saved: OB7000_Technical_Specifications.txt
Generated and saved: OB7000_End_Effector_Compatibility.txt
Generated and saved: OB7000_Power_Requirements_Guide.txt
Generated and saved: OB7000_Error_Code_Reference.txt
Generated and saved: OB7000_Communication_Troubleshooting.txt
Generated and saved: OB7000_Arm_Stall_Troubleshooting.txt
Generated and saved: OB7000_Software_Update_Failure_Recovery.txt

All synthetic documents have been generated and saved.


## Initialize RAG Components


Set up the necessary components for the RAG pipeline. This includes choosing and initializing an embedding model (e.g., a sentence transformer) and selecting an in-memory vector store (e.g., FAISS or ChromaDB) to store document embeddings.


In [2]:
pip install sentence-transformers chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.4/21.4 MB 61.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 16.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 56.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 69.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.0/220.0 kB 15.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 3.5 MB/s eta 0:00:00
  Attempting uninstall: opentelemetry-proto
    Fou

In [3]:
from sentence_transformers import SentenceTransformer

# Initialize the embedding model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Embedding model 'all-MiniLM-L6-v2' initialized successfully.")

# Although not explicitly required to be initialized at this step, we confirm that
# chromadb will be used as the in-memory vector store.
print("ChromaDB will be used as the in-memory vector store for embeddings.")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model 'all-MiniLM-L6-v2' initialized successfully.
ChromaDB will be used as the in-memory vector store for embeddings.


**Reasoning**:
With the embedding model initialized, the next logical step is to load the generated synthetic documents, process them into a format suitable for embedding, generate embeddings using the initialized model, and then store these embeddings in the ChromaDB vector store for efficient retrieval.



In [4]:
import chromadb

# Initialize ChromaDB client and collection
chroma_client = chromadb.Client()
collection = chroma_client.get_or_create_collection(
    name="robotics_documentation",
    metadata={"hnsw:space": "cosine"} # Cosine similarity for embedding comparison
)

# List to hold documents, their IDs, and metadata
documents = []
metadatas = []
ids = []

# Read each generated document and prepare for embedding
for i, filename in enumerate(document_filenames):
    with open(filename, 'r') as f:
        content = f.read()

    # For simplicity, each document is treated as a single chunk.
    # In a real-world scenario, documents would be split into smaller chunks.
    documents.append(content)
    metadatas.append({"source": filename})
    ids.append(f"doc_{i+1}")

# Generate embeddings for the documents and add them to the ChromaDB collection
# ChromaDB will automatically use the `embedding_model` if it's set as the default,
# or we can pass the embeddings explicitly.
# For this example, let's explicitly generate and add them.
embeddings = embedding_model.encode(documents).tolist()

# Add documents to the ChromaDB collection
collection.add(
    documents=documents,
    embeddings=embeddings,
    metadatas=metadatas,
    ids=ids
)

print(f"Added {len(documents)} documents to ChromaDB collection 'robotics_documentation'.")
print(f"Example document ID: {ids[0]}, Source: {metadatas[0]['source']}")

Added 13 documents to ChromaDB collection 'robotics_documentation'.
Example document ID: doc_1, Source: OB7000_Gripper_Operation_Manual.txt


## Chunk and Embed Documents

Refining the document processing by splitting the synthetic documents into smaller, context-coherent chunks and then generating and storing embeddings for these chunks in the ChromaDB vector store.


**Reasoning**:
The first step is to install the `langchain-text-splitters` library as it is required for chunking the documents, and it's not currently installed in the environment.



In [5]:
pip install langchain-text-splitters

**Reasoning**:
Now that `langchain-text-splitters` is installed, I will proceed to clear the existing ChromaDB collection, initialize the `RecursiveCharacterTextSplitter`, iterate through the documents, chunk their content, generate embeddings for each chunk, and finally add these chunked documents with their embeddings and metadata to the ChromaDB collection as per the subtask instructions.



In [6]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
import chromadb

# Access the existing ChromaDB client and collection
chroma_client = chromadb.Client()
collection_name = "robotics_documentation"
collection = chroma_client.get_or_create_collection(name=collection_name)

# Clear existing data from the collection
collection.delete(ids=collection.get()['ids'])
print(f"Cleared existing data from collection '{collection_name}'.")

# Initialize the text splitter
# A good chunk_size for short documents/sections and chunk_overlap to maintain context.
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50,
    length_function=len,
    is_separator_regex=False,
)

# Lists to hold chunked documents, their IDs, embeddings, and metadata
all_chunks = []
all_chunk_metadatas = []
all_chunk_ids = []

# Read each generated document, split into chunks, and prepare for embedding
chunk_id_counter = 0
for filename in document_filenames:
    with open(filename, 'r') as f:
        content = f.read()

    # Split the document into chunks
    chunks = text_splitter.split_text(content)

    for i, chunk in enumerate(chunks):
        all_chunks.append(chunk)
        # Create metadata for each chunk, linking it to its original document and a unique chunk ID
        all_chunk_metadatas.append({"source": filename, "chunk_index": i})
        all_chunk_ids.append(f"{filename.replace('.txt', '')}_chunk_{chunk_id_counter}")
        chunk_id_counter += 1

# Generate embeddings for all chunks
# Ensure embedding_model is available from previous steps
chunk_embeddings = embedding_model.encode(all_chunks).tolist()

# Add all chunks to the ChromaDB collection
collection.add(
    documents=all_chunks,
    embeddings=chunk_embeddings,
    metadatas=all_chunk_metadatas,
    ids=all_chunk_ids
)

print(f"Added {len(all_chunks)} chunks to ChromaDB collection '{collection_name}'.")
print(f"Example chunk ID: {all_chunk_ids[0]}, Source: {all_chunk_metadatas[0]['source']}, Chunk Index: {all_chunk_metadatas[0]['chunk_index']}")
print(f"Total unique documents in collection: {len(set([m['source'] for m in all_chunk_metadatas]))}")

Cleared existing data from collection 'robotics_documentation'.
Added 38 chunks to ChromaDB collection 'robotics_documentation'.
Example chunk ID: OB7000_Gripper_Operation_Manual_chunk_0, Source: OB7000_Gripper_Operation_Manual.txt, Chunk Index: 0
Total unique documents in collection: 13


## Implement Retrieval and Response Generation

Develop a function that takes a user query, retrieves the most relevant document chunks from the vector store, and then uses a Large Language Model (LLM) to generate a coherent and contextually relevant response based on the retrieved information. This will be the core RAG logic.


In [7]:
import os
import google.generativeai as genai

# Configure Google API key from environment variables
# Ensure you have your GOOGLE_API_KEY set up in your environment
# For Colab, you can add it via `from google.colab import userdata; os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')`
genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

# Ensure embedding_model and collection are available from previous steps
# embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
# chroma_client = chromadb.Client()
# collection = chroma_client.get_or_create_collection(name="robotics_documentation")

def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model
    model = genai.GenerativeModel('gemini-pro')

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.
    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.

    Retrieved Context:
    {context}

    User Query: {query}

    Answer:"""

    # 7. Generate a response from the LLM
    try:
        response = model.generate_content(prompt)
        llm_response = response.text
    except Exception as e:
        llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames

print("RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.")

RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.


/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning: 

All support for the `google.generativeai` package has ended. It will no longer be receiving 
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)


In [8]:
print("Demonstrating the RAG system with example queries.")

# Example Query 1: Information about gripper operation
query1 = "How do I operate the OB-7000's gripper?"
response1, sources1 = rag_query(query1)
print(f"\nQuery: {query1}")
print(f"Response: {response1}")
print(f"Sources: {', '.join(sources1)}")

# Example Query 2: Safety protocols for human-robot collaboration
query2 = "What are the safety guidelines for human-robot collaboration with the OB-7000?"
response2, sources2 = rag_query(query2)
print(f"\nQuery: {query2}")
print(f"Response: {response2}")
print(f"Sources: {', '.join(sources2)}")

# Example Query 3: Troubleshooting an arm stall
query3 = "My OB-7000 arm stalled. What should I do?"
response3, sources3 = rag_query(query3)
print(f"\nQuery: {query3}")
print(f"Response: {response3}")
print(f"Sources: {', '.join(sources3)}")

# Example Query 4: Information not directly in documents
query4 = "What is the best color for the OB-7000?"
response4, sources4 = rag_query(query4)
print(f"\nQuery: {query4}")
print(f"Response: {response4}")
print(f"Sources: {', '.join(sources4) if sources4 else 'None'}")

Demonstrating the RAG system with example queries.

Query: How do I operate the OB-7000's gripper?
Response: Error generating LLM response: 
  No API_KEY or ADC found. Please either:
    - Set the `GOOGLE_API_KEY` environment variable.
    - Manually pass the key with `genai.configure(api_key=my_api_key)`.
    - Or set up Application Default Credentials, see https://ai.google.dev/gemini-api/docs/oauth for more information.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Software_Update_Failure_Recovery.txt

Query: What are the safety guidelines for human-robot collaboration with the OB-7000?
Response: Error generating LLM response: 
  No API_KEY or ADC found. Please either:
    - Set the `GOOGLE_API_KEY` environment variable.
    - Manually pass the key with `genai.configure(api_key=my_api_key)`.
    - Or set up Application Default Credentials, see https://ai.google.dev/gemini-api/docs/oauth for more information.
Sources: OB7000_Human_Robot_Collaboration_Safety.txt, OB7000_Technic

In [10]:
import os
from google.colab import userdata
import google.generativeai as genai

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    # Reconfigure genai with whatever is in the environment (likely still None for API key)
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

print("Demonstrating the RAG system with example queries.")

# Example Query 1: Information about gripper operation
query1 = "How do I operate the OB-7000's gripper?"
response1, sources1 = rag_query(query1)
print(f"\nQuery: {query1}")
print(f"Response: {response1}")
print(f"Sources: {', '.join(sources1)}")

# Example Query 2: Safety protocols for human-robot collaboration
query2 = "What are the safety guidelines for human-robot collaboration with the OB-7000?"
response2, sources2 = rag_query(query2)
print(f"\nQuery: {query2}")
print(f"Response: {response2}")
print(f"Sources: {', '.join(sources2)}")

# Example Query 3: Troubleshooting an arm stall
query3 = "My OB-7000 arm stalled. What should I do?"
response3, sources3 = rag_query(query3)
print(f"\nQuery: {query3}")
print(f"Response: {response3}")
print(f"Sources: {', '.join(sources3)}")

# Example Query 4: Information not directly in documents
query4 = "What is the best color for the OB-7000?"
response4, sources4 = rag_query(query4)
print(f"\nQuery: {query4}")
print(f"Response: {response4}")
print(f"Sources: {', '.join(sources4) if sources4 else 'None'}")

LLM functionality may be impaired as API key is not configured.
Demonstrating the RAG system with example queries.

Query: How do I operate the OB-7000's gripper?
Response: Error generating LLM response: 
  No API_KEY or ADC found. Please either:
    - Set the `GOOGLE_API_KEY` environment variable.
    - Manually pass the key with `genai.configure(api_key=my_api_key)`.
    - Or set up Application Default Credentials, see https://ai.google.dev/gemini-api/docs/oauth for more information.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Software_Update_Failure_Recovery.txt

Query: What are the safety guidelines for human-robot collaboration with the OB-7000?
Response: Error generating LLM response: 
  No API_KEY or ADC found. Please either:
    - Set the `GOOGLE_API_KEY` environment variable.
    - Manually pass the key with `genai.configure(api_key=my_api_key)`.
    - Or set up Application Default Credentials, see https://ai.google.dev/gemini-api/docs/oauth for more information.
Sour

## Demonstrate RAG System with Example Queries

### Subtask:
Execute the implemented RAG system with example queries to showcase its end-to-end functionality (retrieval and response generation).


### Instructions to set up GOOGLE_API_KEY:

1.  **Add `GOOGLE_API_KEY` to Colab secrets:** Click on the 'key' icon in the left sidebar (Secrets panel), then click '+ New secret', enter `GOOGLE_API_KEY` as the name and paste your API key as the value. Make sure 'Notebook access' is checked.
2.  **Run the following code cell** that attempts to retrieve the `GOOGLE_API_KEY` from Colab secrets and configures `google.generativeai`.

**Reasoning**:
The previous code block `4df35d40` attempted to configure the `GOOGLE_API_KEY` and execute example queries, but it did not include all the new queries specified by the user. Therefore, I will create a new code block that incorporates the `GOOGLE_API_KEY` setup (with a `try-except` for user experience) and executes all the example queries, both old and new, to fully demonstrate the RAG system's functionality as required by the subtask.



In [11]:
import os
from google.colab import userdata
import google.generativeai as genai

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    # Reconfigure genai with whatever is in the environment (likely still None for API key)
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

print("\nDemonstrating the RAG system with example queries.")

# Define all example queries
example_queries = [
    "How should the robot handle fragile items?",
    "What's the maximum weight capacity for gripper arm?",
    "What safety checks are needed before moving hazardous materials?",
    "How do I operate the OB-7000's gripper?",
    "What are the safety guidelines for human-robot collaboration with the OB-7000?",
    "My OB-7000 arm stalled. What should I do?",
    "What is the best color for the OB-7000?"
]

for i, query in enumerate(example_queries):
    print(f"\n--- Query {i+1} ---")
    response, sources = rag_query(query)
    print(f"Query: {query}")
    print(f"Response: {response}")
    print(f"Sources: {', '.join(sources) if sources else 'None'}")


LLM functionality may be impaired as API key is not configured.

Demonstrating the RAG system with example queries.

--- Query 1 ---
Query: How should the robot handle fragile items?
Response: Error generating LLM response: 
  No API_KEY or ADC found. Please either:
    - Set the `GOOGLE_API_KEY` environment variable.
    - Manually pass the key with `genai.configure(api_key=my_api_key)`.
    - Or set up Application Default Credentials, see https://ai.google.dev/gemini-api/docs/oauth for more information.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 2 ---
Query: What's the maximum weight capacity for gripper arm?
Response: Error generating LLM response: 
  No API_KEY or ADC found. Please either:
    - Set the `GOOGLE_API_KEY` environment variable.
    - Manually pass the key with `genai.configure(api_key=my_api_key)`.
    - Or set up Application Default Credentials, see https://ai.google.dev/gemini-api/docs/oauth for more informa

In [12]:
from google.colab import userdata

# Retrieve the API key from Colab Secrets
GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')

# Use the key to configure your API client (example for the Gemini API)
# import google.generativeai as genai
# genai.configure(api_key=GOOGLE_API_KEY)


In [14]:
import os
from google.colab import userdata
import google.generativeai as genai

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    # Reconfigure genai with whatever is in the environment (likely still None for API key)
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

print("\nDemonstrating the RAG system with example queries.")

# Define all example queries
example_queries = [
    "How should the robot handle fragile items?",
    "What's the maximum weight capacity for gripper arm?",
    "What safety checks are needed before moving hazardous materials?",
    "How do I operate the OB-7000's gripper?",
    "What are the safety guidelines for human-robot collaboration with the OB-7000?",
    "My OB-7000 arm stalled. What should I do?",
    "What is the best color for the OB-7000?"
]

for i, query in enumerate(example_queries):
    print(f"\n--- Query {i+1} ---")
    response, sources = rag_query(query)
    print(f"Query: {query}")
    print(f"Response: {response}")
    print(f"Sources: {', '.join(sources) if sources else 'None'}")


Google API Key set from Colab secrets and genai re-configured.

Demonstrating the RAG system with example queries.

--- Query 1 ---


Query: How should the robot handle fragile items?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 2 ---


Query: What's the maximum weight capacity for gripper arm?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Payload_Limits_Guide.txt

--- Query 3 ---


Query: What safety checks are needed before moving hazardous materials?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Human_Robot_Collaboration_Safety.txt

--- Query 4 ---


Query: How do I operate the OB-7000's gripper?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 5 ---


Query: What are the safety guidelines for human-robot collaboration with the OB-7000?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Human_Robot_Collaboration_Safety.txt, OB7000_Technical_Specifications.txt

--- Query 6 ---


Query: My OB-7000 arm stalled. What should I do?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 7 ---
Query: What is the best color for the OB-7000?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Human_Robot_Collaboration_Safety.txt, OB7000_Technical_Specifications.txt, OB7000_Vision_S

**Reasoning**:
The previous code execution resulted in a '404 models/gemini-pro is not found' error, indicating the model name or version might be incorrect or unavailable. I will update the model name to 'gemini-1.0-pro' within the `rag_query` function, which is often the current stable text generation model in the Google Generative AI API.



In [15]:
import os
import google.generativeai as genai

# Configure Google API key from environment variables
# Ensure you have your GOOGLE_API_KEY set up in your environment
# For Colab, you can add it via `from google.colab import userdata; os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')`
genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

# Ensure embedding_model and collection are available from previous steps
# embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
# chroma_client = chromadb.Client()
# collection = chroma_client.get_or_create_collection(name="robotics_documentation")

def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with 'gemini-1.0-pro'
    model = genai.GenerativeModel('gemini-1.0-pro')

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.
    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.

    Retrieved Context:
    {context}

    User Query: {query}

    Answer:"""

    # 7. Generate a response from the LLM
    try:
        response = model.generate_content(prompt)
        llm_response = response.text
    except Exception as e:
        llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames

print("RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.")

RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.


**Reasoning**:
The `rag_query` function has been redefined with the correct LLM model. Now, I will re-execute the code block that runs all the example queries to verify that the RAG system is functioning correctly with the updated model.



In [16]:
import os
from google.colab import userdata
import google.generativeai as genai

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    # Reconfigure genai with whatever is in the environment (likely still None for API key)
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

print("\nDemonstrating the RAG system with example queries.")

# Define all example queries
example_queries = [
    "How should the robot handle fragile items?",
    "What's the maximum weight capacity for gripper arm?",
    "What safety checks are needed before moving hazardous materials?",
    "How do I operate the OB-7000's gripper?",
    "What are the safety guidelines for human-robot collaboration with the OB-7000?",
    "My OB-7000 arm stalled. What should I do?",
    "What is the best color for the OB-7000?"
]

for i, query in enumerate(example_queries):
    print(f"\n--- Query {i+1} ---")
    response, sources = rag_query(query)
    print(f"Query: {query}")
    print(f"Response: {response}")
    print(f"Sources: {', '.join(sources) if sources else 'None'}")

Google API Key set from Colab secrets and genai re-configured.

Demonstrating the RAG system with example queries.

--- Query 1 ---


Query: How should the robot handle fragile items?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-1.0-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 2 ---


Query: What's the maximum weight capacity for gripper arm?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-1.0-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Payload_Limits_Guide.txt

--- Query 3 ---


Query: What safety checks are needed before moving hazardous materials?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-1.0-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Human_Robot_Collaboration_Safety.txt

--- Query 4 ---


Query: How do I operate the OB-7000's gripper?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-1.0-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 5 ---


Query: What are the safety guidelines for human-robot collaboration with the OB-7000?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-1.0-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Human_Robot_Collaboration_Safety.txt, OB7000_Technical_Specifications.txt

--- Query 6 ---


Query: My OB-7000 arm stalled. What should I do?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-1.0-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 7 ---
Query: What is the best color for the OB-7000?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-1.0-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Human_Robot_Collaboration_Safety.txt, OB7000_Technical_Specifications.txt,

In [17]:
import os
import google.generativeai as genai

# Configure Google API key from environment variables
# Ensure you have your GOOGLE_API_KEY set up in your environment
# For Colab, you can add it via `from google.colab import userdata; os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')`
genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

# Ensure embedding_model and collection are available from previous steps
# embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
# chroma_client = chromadb.Client()
# collection = chroma_client.get_or_create_collection(name="robotics_documentation")

def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with 'gemini-pro'
    model = genai.GenerativeModel('gemini-pro')

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.
    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.

    Retrieved Context:
    {context}

    User Query: {query}

    Answer:"""

    # 7. Generate a response from the LLM
    try:
        response = model.generate_content(prompt)
        llm_response = response.text
    except Exception as e:
        llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames

print("RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.")

RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.



The `rag_query` function has been redefined with the correct LLM model. Now, I will re-execute the code block that runs all the example queries to verify that the RAG system is functioning correctly with the updated model.



In [18]:
import os
from google.colab import userdata
import google.generativeai as genai

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    # Reconfigure genai with whatever is in the environment (likely still None for API key)
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

print("\nDemonstrating the RAG system with example queries.")

# Define all example queries
example_queries = [
    "How should the robot handle fragile items?",
    "What's the maximum weight capacity for gripper arm?",
    "What safety checks are needed before moving hazardous materials?",
    "How do I operate the OB-7000's gripper?",
    "What are the safety guidelines for human-robot collaboration with the OB-7000?",
    "My OB-7000 arm stalled. What should I do?",
    "What is the best color for the OB-7000?"
]

for i, query in enumerate(example_queries):
    print(f"\n--- Query {i+1} ---")
    response, sources = rag_query(query)
    print(f"Query: {query}")
    print(f"Response: {response}")
    print(f"Sources: {', '.join(sources) if sources else 'None'}")

Google API Key set from Colab secrets and genai re-configured.

Demonstrating the RAG system with example queries.

--- Query 1 ---


Query: How should the robot handle fragile items?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 2 ---


Query: What's the maximum weight capacity for gripper arm?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Payload_Limits_Guide.txt

--- Query 3 ---


Query: What safety checks are needed before moving hazardous materials?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Human_Robot_Collaboration_Safety.txt

--- Query 4 ---


Query: How do I operate the OB-7000's gripper?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 5 ---


Query: What are the safety guidelines for human-robot collaboration with the OB-7000?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Human_Robot_Collaboration_Safety.txt, OB7000_Technical_Specifications.txt

--- Query 6 ---


Query: My OB-7000 arm stalled. What should I do?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 7 ---


Query: What is the best color for the OB-7000?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Human_Robot_Collaboration_Safety.txt, OB7000_Technical_Specifications.txt, OB7000_Vision_System_Calibration.txt


**Reasoning**:
The previous code execution for `rag_query` consistently resulted in a '404 models/gemini-pro is not found' error, even after attempting to switch to 'gemini-1.0-pro' and back to 'gemini-pro'. This indicates that the specific model name might be unavailable for the current API version, region, or due to a temporary API issue. As a next troubleshooting step to resolve the 404 error and allow for successful LLM response generation, I will update the model name within the `rag_query` function to 'text-bison-001', which is another commonly available text generation model in the Google Generative AI API.



In [19]:
import os
import google.generativeai as genai

# Configure Google API key from environment variables
# Ensure you have your GOOGLE_API_KEY set up in your environment
# For Colab, you can add it via `from google.colab import userdata; os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')`
genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

# Ensure embedding_model and collection are available from previous steps
# embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
# chroma_client = chromadb.Client()
# collection = chroma_client.get_or_create_collection(name="robotics_documentation")

def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with 'text-bison-001'
    model = genai.GenerativeModel('text-bison-001')

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.
    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.

    Retrieved Context:
    {context}

    User Query: {query}

    Answer:"""

    # 7. Generate a response from the LLM
    try:
        response = model.generate_content(prompt)
        llm_response = response.text
    except Exception as e:
        llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames

print("RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.")

RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.


**Reasoning**:
The `rag_query` function has been redefined with the `text-bison-001` LLM model. Now, I will re-execute the code block that runs all the example queries to verify that the RAG system is functioning correctly with this updated model.



In [20]:
import os
from google.colab import userdata
import google.generativeai as genai

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    # Reconfigure genai with whatever is in the environment (likely still None for API key)
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

print("\nDemonstrating the RAG system with example queries.")

# Define all example queries
example_queries = [
    "How should the robot handle fragile items?",
    "What's the maximum weight capacity for gripper arm?",
    "What safety checks are needed before moving hazardous materials?",
    "How do I operate the OB-7000's gripper?",
    "What are the safety guidelines for human-robot collaboration with the OB-7000?",
    "My OB-7000 arm stalled. What should I do?",
    "What is the best color for the OB-7000?"
]

for i, query in enumerate(example_queries):
    print(f"\n--- Query {i+1} ---")
    response, sources = rag_query(query)
    print(f"Query: {query}")
    print(f"Response: {response}")
    print(f"Sources: {', '.join(sources) if sources else 'None'}")

Google API Key set from Colab secrets and genai re-configured.

Demonstrating the RAG system with example queries.

--- Query 1 ---


Query: How should the robot handle fragile items?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/text-bison-001:generateContent?%24alt=json%3Benum-encoding%3Dint: models/text-bison-001 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 2 ---


Query: What's the maximum weight capacity for gripper arm?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/text-bison-001:generateContent?%24alt=json%3Benum-encoding%3Dint: models/text-bison-001 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Payload_Limits_Guide.txt

--- Query 3 ---


Query: What safety checks are needed before moving hazardous materials?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/text-bison-001:generateContent?%24alt=json%3Benum-encoding%3Dint: models/text-bison-001 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Human_Robot_Collaboration_Safety.txt

--- Query 4 ---


Query: How do I operate the OB-7000's gripper?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/text-bison-001:generateContent?%24alt=json%3Benum-encoding%3Dint: models/text-bison-001 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Gripper_Operation_Manual.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 5 ---


Query: What are the safety guidelines for human-robot collaboration with the OB-7000?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/text-bison-001:generateContent?%24alt=json%3Benum-encoding%3Dint: models/text-bison-001 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Human_Robot_Collaboration_Safety.txt, OB7000_Technical_Specifications.txt

--- Query 6 ---


Query: My OB-7000 arm stalled. What should I do?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/text-bison-001:generateContent?%24alt=json%3Benum-encoding%3Dint: models/text-bison-001 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Arm_Stall_Troubleshooting.txt, OB7000_Software_Update_Failure_Recovery.txt

--- Query 7 ---


Query: What is the best color for the OB-7000?
Response: Error generating LLM response: 404 POST https://generativelanguage.googleapis.com/v1beta/models/text-bison-001:generateContent?%24alt=json%3Benum-encoding%3Dint: models/text-bison-001 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
Sources: OB7000_Human_Robot_Collaboration_Safety.txt, OB7000_Technical_Specifications.txt, OB7000_Vision_System_Calibration.txt


**Reasoning**:
The previous code execution consistently failed with a 404 error, indicating that the specified LLM models are not found or supported. To resolve this, I will use `genai.list_models()` to dynamically check which generative models are actually available and supported for `generateContent` method in the current environment, and then update the `rag_query` function to use a supported model.



In [22]:
import os
import google.generativeai as genai

# Configure Google API key from environment variables
# Ensure you have your GOOGLE_API_KEY set up in your environment
# For Colab, you can add it via `from google.colab import userdata; os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')`
genai.configure(api_key=os.environ.get('AIzaSyDuchZSM1iyE8aisFMydZmXEfGKFkchfOU'))

# Ensure embedding_model and collection are available from previous steps
# embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
# chroma_client = chromadb.Client()
# collection = chroma_client.get_or_create_collection(name="robotics_documentation")

def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with a supported model
    # Dynamically find a suitable model supporting 'generateContent'
    try:
        available_models = genai.list_models()
        # Prioritize 'gemini-pro' as it's typically the most capable and common
        supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods and 'gemini-pro' in m.name), None)
        if not supported_model_name:
            # Fallback to any other model that supports generateContent
            supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods), None)

        if not supported_model_name:
            raise ValueError("No generative model found that supports 'generateContent'.")

        model = genai.GenerativeModel(supported_model_name)
        print(f"Using LLM model: {supported_model_name}")

    except Exception as e:
        print(f"Error listing or selecting LLM model: {e}")
        # Fallback to a hardcoded model name if listing fails, or re-raise
        # For now, we'll use a placeholder error and let the generate_content catch it.
        model = None # Ensure model is None if selection fails

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.
    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.

    Retrieved Context:
    {context}

    User Query: {query}

    Answer:"""

    # 7. Generate a response from the LLM
    llm_response = "Error: LLM model not initialized properly." # Default error message
    if model:
        try:
            response = model.generate_content(prompt)
            llm_response = response.text
        except Exception as e:
            llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames

print("RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.")

RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.


**Reasoning**:
The `rag_query` function has been updated to dynamically select an available LLM model. Now, I will re-execute the code block that runs all the example queries to verify that the RAG system is functioning correctly with this updated model.



In [23]:
import os
from google.colab import userdata
import google.generativeai as genai

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    # Reconfigure genai with whatever is in the environment (likely still None for API key)
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

print("\nDemonstrating the RAG system with example queries.")

# Define all example queries
example_queries = [
    "How should the robot handle fragile items?",
    "What's the maximum weight capacity for gripper arm?",
    "What safety checks are needed before moving hazardous materials?",
    "How do I operate the OB-7000's gripper?",
    "What are the safety guidelines for human-robot collaboration with the OB-7000?",
    "My OB-7000 arm stalled. What should I do?",
    "What is the best color for the OB-7000?"
]

for i, query in enumerate(example_queries):
    print(f"\n--- Query {i+1} ---")
    response, sources = rag_query(query)
    print(f"Query: {query}")
    print(f"Response: {response}")
    print(f"Sources: {', '.join(sources) if sources else 'None'}")

Google API Key set from Colab secrets and genai re-configured.

Demonstrating the RAG system with example queries.

--- Query 1 ---
Using LLM model: models/gemini-pro-latest


Query: How should the robot handle fragile items?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-

Query: What's the maximum weight capacity for gripper arm?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: 

Query: What safety checks are needed before moving hazardous materials?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limi

Query: How do I operate the OB-7000's gripper?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro

Query: What are the safety guidelines for human-robot collaboration with the OB-7000?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_tok

Query: My OB-7000 arm stalled. What should I do?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-p

Query: What is the best color for the OB-7000?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro

**Reasoning**:
The previous `rag_query` function definition in cell `6649708a` had an incorrect `genai.configure` call, which might have led to issues with API key configuration. I will correct this to ensure the API key is properly picked up from the environment.



In [24]:
import os
import google.generativeai as genai

# Configure Google API key from environment variables
# Ensure you have your GOOGLE_API_KEY set up in your environment
# For Colab, you can add it via `from google.colab import userdata; os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')`
genai.configure(api_key=os.environ.get('GOOGLE_API_KEY')) # Corrected: using GOOGLE_API_KEY from environment

# Ensure embedding_model and collection are available from previous steps
# embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
# chroma_client = chromadb.Client()
# collection = chroma_client.get_or_create_collection(name="robotics_documentation")

def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with a supported model
    # Dynamically find a suitable model supporting 'generateContent'
    try:
        available_models = genai.list_models()
        # Prioritize 'gemini-pro' as it's typically the most capable and common
        supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods and 'gemini-pro' in m.name), None)
        if not supported_model_name:
            # Fallback to any other model that supports generateContent
            supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods), None)

        if not supported_model_name:
            raise ValueError("No generative model found that supports 'generateContent'.")

        model = genai.GenerativeModel(supported_model_name)
        print(f"Using LLM model: {supported_model_name}")

    except Exception as e:
        print(f"Error listing or selecting LLM model: {e}")
        # Fallback to a hardcoded model name if listing fails, or re-raise
        # For now, we'll use a placeholder error and let the generate_content catch it.
        model = None # Ensure model is None if selection fails

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.
    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.

    Retrieved Context:
    {context}

    User Query: {query}

    Answer:"""

    # 7. Generate a response from the LLM
    llm_response = "Error: LLM model not initialized properly." # Default error message
    if model:
        try:
            response = model.generate_content(prompt)
            llm_response = response.text
        except Exception as e:
            llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames

print("RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.")

RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.


In [27]:
### API Quota Exceeded

######The previous attempts to generate responses using the Google Generative AI API failed due to a 'Quota exceeded' error. This means that your API key has reached its usage limits.

###**To resolve this, you can:**
###1.  **Wait:** Quotas often reset periodically (e.g., daily). You can try running the queries again after some time.
###2.  **Check your Google Cloud project's billing and quotas:** If you are on a free tier, you might have limited requests. Consider upgrading your plan or requesting a quota increase if this is a recurring issue. You can monitor your usage and quotas at [https://ai.google.dev/gemini-api/docs/rate-limits](https://ai.google.dev/gemini-api/docs/rate-limits).

###Once your quota is reset or increased, you can re-run the demonstration cell below.

### API Quota Exceeded

The previous attempts to generate responses using the Google Generative AI API failed due to a 'Quota exceeded' error. This means that your API key has reached its usage limits.

### **To resolve this, you can:**
1.  **Wait:** Quotas often reset periodically (e.g., daily). You can try running the queries again after some time.
2.  **Check your Google Cloud project's billing and quotas:** If you are on a free tier, you might have limited requests. Consider upgrading your plan or requesting a quota increase if this is a recurring issue. You can monitor your usage and quotas at [https://ai.google.dev/gemini-api/docs/rate-limits](https://ai.google.dev/gemini-api/docs/rate-limits).

### Once your quota is reset or increased, you can re-run the demonstration cell below.

In [31]:
import os
from google.colab import userdata
import google.generativeai as genai

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    # Reconfigure genai with whatever is in the environment (likely still None for API key)
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

print("\nDemonstrating the RAG system with example queries.")

# Define all example queries
example_queries = [
    "How should the robot handle fragile items?",
    "What's the maximum weight capacity for gripper arm?",
    "What safety checks are needed before moving hazardous materials?",
    "How do I operate the OB-7000's gripper?",
    "What are the safety guidelines for human-robot collaboration with the OB-7000?",
    "My OB-7000 arm stalled. What should I do?",
    "What is the best color for the OB-7000?"
]

for i, query in enumerate(example_queries):
    print(f"\n--- Query {i+1} ---")
    response, sources = rag_query(query)
    print(f"Query: {query}")
    print(f"Response: {response}")
    print(f"Sources: {', '.join(sources) if sources else 'None'}")

Google API Key set from Colab secrets and genai re-configured.

Demonstrating the RAG system with example queries.

--- Query 1 ---
Using LLM model: models/gemini-pro-latest


Query: How should the robot handle fragile items?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-

Query: What's the maximum weight capacity for gripper arm?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: 

Query: What safety checks are needed before moving hazardous materials?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limi

Query: How do I operate the OB-7000's gripper?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro

Query: What are the safety guidelines for human-robot collaboration with the OB-7000?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_tok

Query: My OB-7000 arm stalled. What should I do?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-p

Query: What is the best color for the OB-7000?
Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro

#RAG Architecture Explanation




## RAG System Architecture Explanation

The Retrieval-Augmented Generation (RAG) system implemented in this notebook is designed to provide context-aware responses to user queries based on a corpus of robotics documentation. The architecture comprises several key components:

1.  **Document Chunking Strategy:** The raw text documents are first processed using `RecursiveCharacterTextSplitter` from `langchain-text-splitters`. This strategy is chosen for its ability to split text by various delimiters, ensuring that context is maintained within chunks. Each document is split into smaller, coherent chunks with a `chunk_size` of 500 characters and a `chunk_overlap` of 50 characters. This overlap helps to preserve semantic continuity between adjacent chunks, preventing loss of context at chunk boundaries.

2.  **Embedding Model:** For transforming text into numerical vector representations, the 'all-MiniLM-L6-v2' model from the `sentence-transformers` library is utilized. This model is a compact yet powerful pre-trained model known for generating high-quality sentence embeddings efficiently, making it suitable for capturing the semantic meaning of the document chunks and user queries.

3.  **Vector Store Implementation:** ChromaDB serves as the in-memory vector store for this RAG system. After chunking, each text chunk is embedded using the 'all-MiniLM-L6-v2' model, and these embeddings are then stored in a ChromaDB collection named "robotics_documentation". Cosine similarity is used for retrieval, allowing the system to find text chunks that are semantically most similar to the user's query embedding.

4.  **LLM Integration for Response Generation:** The system integrates a Large Language Model (LLM) from Google Generative AI to synthesize answers. The `rag_query` function dynamically identifies an available and supported generative model (e.g., `gemini-pro-latest`) from `genai.list_models()`. It constructs a prompt that includes the user's query alongside the context retrieved from ChromaDB. The LLM then generates a coherent and contextually relevant response based on this enriched prompt, ensuring that answers are grounded in the provided documentation.

## Define RAG Performance Metrics

### Subtask:
Identify and define key performance metrics for the RAG system. These metrics could include relevance of retrieved documents, factual correctness of generated responses, coherence, fluency, and completeness of the answers. We should consider both quantitative and qualitative aspects.

### Quantitative Metrics:

1.  **Retrieval Precision/Recall (R@K, P@K, F1@K):**
    *   **Definition:** Measures how effective the retriever is at finding relevant documents for a given query.
        *   **Precision@K (P@K):** Proportion of retrieved documents that are relevant among the top K documents.
        *   **Recall@K (R@K):** Proportion of relevant documents found among the top K documents, out of all possible relevant documents.
        *   **F1@K:** Harmonic mean of Precision and Recall.
    *   **Measurement:** Requires a ground truth dataset of queries, relevant documents, and document chunks. Can be automated by comparing retrieved chunks against pre-labeled relevant chunks for each query.

2.  **Factual Accuracy:**
    *   **Definition:** The percentage of generated answers that are factually correct and supported by the retrieved source documents.
    *   **Measurement:** Can be assessed through human evaluation (binary true/false or a multi-point scale for correctness) or by using LLM-based evaluators that compare the generated response to the source context for factual consistency.

3.  **Completeness:**
    *   **Definition:** The degree to which the generated answer addresses all aspects of the query, given the available context, without omitting crucial information.
    *   **Measurement:** Primarily a qualitative metric often assessed by human evaluators using a rating scale (e.g., 1-5) or by LLM-based evaluation that checks if all sub-questions or requirements of the query have been met by the response.

### Qualitative Metrics:

1.  **Relevance of Retrieved Documents:**
    *   **Definition:** Human judgment on whether the top-k retrieved documents are truly helpful, necessary, and sufficiently comprehensive for answering the query.
    *   **Measurement:** Human annotation where evaluators rate the relevance of each retrieved chunk to the query (e.g., highly relevant, somewhat relevant, not relevant).

2.  **Coherence and Fluency:**
    *   **Definition:** How natural, readable, grammatically correct, and well-structured the generated response is. It should flow logically and be easy for a human to understand.
    *   **Measurement:** Human evaluation based on a multi-point scale (e.g., 1-5 for fluency and coherence). LLM-based evaluation can also provide scores for these aspects.

3.  **Conciseness:**
    *   **Definition:** Whether the response directly answers the question without unnecessary verbosity, repetition, or irrelevant information.
    *   **Measurement:** Human evaluation on a rating scale (e.g., 1-5) for conciseness. Can also be partially measured by token count or sentence count relative to information density.

4.  **Groundedness/Attribution:**
    *   **Definition:** The extent to which the answer relies solely on the provided context and avoids hallucination (generating information not present in the sources). This also includes the ability to attribute information back to its source.
    *   **Measurement:** Human evaluation checking if every statement in the response is directly supported by the retrieved documents. LLM-based evaluators can also be prompted to identify ungrounded statements or verify citations.

## Prepare Evaluation Dataset

### Subtask:
Create a new set of evaluation queries, distinct from the demonstration queries, along with their expected or ideal reference answers. This dataset will serve as the ground truth for evaluating the RAG system's performance against defined metrics.


**Reasoning**:
To prepare the evaluation dataset as specified, I will define a list of dictionaries, where each dictionary contains a new evaluation query and its corresponding reference answer derived from the synthetic robotics documents.



In [1]:
evaluation_dataset = [
    {
        "query": "What are the two main operation modes of the OB-7000's gripper and when should each be used?",
        "reference_answer": "The OB-7000's gripper has two operation modes: Force-Controlled Mode, ideal for delicate objects, and Position-Controlled Mode, best for rigid objects requiring specific grip width."
    },
    {
        "query": "How often should the vision system be calibrated, and what are some best practices?",
        "reference_answer": "The vision system calibration should be performed weekly or after any mechanical adjustment. Best practices include calibrating in consistent lighting conditions and avoiding glare on the target."
    },
    {
        "query": "What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?",
        "reference_answer": "The maximum rated payload for the OB-7000 manipulator arm is 10 kg. For speeds exceeding 75% of max speed, the payload should be reduced by 20%."
    },
    {
        "query": "Describe the steps to restart the OB-7000 after an emergency stop.",
        "reference_answer": "To restart after an E-Stop: 1. Clear the hazard. 2. Twist the pressed E-Stop button clockwise to release it. 3. Reset the safety system on the teach pendant. 4. Initiate 'Power On' from the teach pendant or control panel."
    },
    {
        "query": "What are the physical dimensions and primary power requirements of the OmniBot 7000?",
        "reference_answer": "The OB-7000 has a footprint of 300 mm x 300 mm. Its primary power input is 200-240 VAC, single-phase, 50/60 Hz, and requires a 10 Amps dedicated circuit."
    },
    {
        "query": "What types of end-effectors are compatible with the OB-7000, and what electrical interface do they typically use?",
        "reference_answer": "The OB-7000 is compatible with standard grippers, welding torches, vision systems (e.g., EyeBot 3000 series), and force/torque sensors. The tool flange provides standard M8 connectors for electrical signals (24V DC, I/O)."
    },
    {
        "query": "What does error code E101 signify and what is the recommended action to resolve it?",
        "reference_answer": "Error code E101 signifies 'Joint Limit Exceeded'. This means the robot arm attempted to move beyond its physical joint limits. The recommended action is to check the program path, manually move the robot within limits using freedrive, and then reset the error."
    }
]

print(f"Created evaluation dataset with {len(evaluation_dataset)} queries.")

Created evaluation dataset with 7 queries.


## Implement RAG Evaluation Logic


Develop a function or script that systematically takes each query from the evaluation dataset, feeds it to the `rag_query` function, and then captures the generated response. It should also include logic to compare the generated response with the reference answer using the defined performance metrics.



I will define the `evaluate_rag_system` function as described, which will iterate through the `evaluation_dataset`, call `rag_query` for each item with error handling, and collect the results for further analysis.



In [2]:
def evaluate_rag_system(dataset):
    """
    Evaluates the RAG system by processing each query in the dataset,
    retrieving a response, and storing the results.
    """
    evaluation_results = []
    for i, item in enumerate(dataset):
        query = item['query']
        reference_answer = item['reference_answer']

        print(f"\nProcessing evaluation query {i+1}/{len(dataset)}: {query}")

        generated_response = ""
        retrieved_sources = []
        try:
            generated_response, retrieved_sources = rag_query(query)
        except Exception as e:
            generated_response = f"Error during RAG query: {e}"
            print(f"Error processing query '{query}': {e}")

        evaluation_results.append({
            'query': query,
            'reference_answer': reference_answer,
            'generated_response': generated_response,
            'retrieved_sources': retrieved_sources
        })

    return evaluation_results

print("RAG evaluation function 'evaluate_rag_system' defined.")

RAG evaluation function 'evaluate_rag_system' defined.


In [3]:
print("Starting RAG system evaluation...")
evaluation_results = evaluate_rag_system(evaluation_dataset)
print("Evaluation complete. Results stored in 'evaluation_results'.")

# Display a sample of the evaluation results
print("\nSample Evaluation Results (first 2 queries):")
for i, result in enumerate(evaluation_results[:2]):
    print(f"--- Query {i+1} ---")
    print(f"Query: {result['query']}")
    print(f"Reference Answer: {result['reference_answer']}")
    print(f"Generated Response: {result['generated_response']}")
    print(f"Retrieved Sources: {', '.join(result['retrieved_sources']) if result['retrieved_sources'] else 'None'}")

Starting RAG system evaluation...

Processing evaluation query 1/7: What are the two main operation modes of the OB-7000's gripper and when should each be used?
Error processing query 'What are the two main operation modes of the OB-7000's gripper and when should each be used?': name 'rag_query' is not defined

Processing evaluation query 2/7: How often should the vision system be calibrated, and what are some best practices?
Error processing query 'How often should the vision system be calibrated, and what are some best practices?': name 'rag_query' is not defined

Processing evaluation query 3/7: What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?
Error processing query 'What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?': name 'rag_query' is not defined

Processing evaluation query 4/7: Describe the steps to restart the OB-7000 after an emergency stop.
Error processing query 'Describe th

In [4]:
import os
import google.generativeai as genai

# Configure Google API key from environment variables
# Ensure you have your GOOGLE_API_KEY set up in your environment
# For Colab, you can add it via `from google.colab import userdata; os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')`
genai.configure(api_key=os.environ.get('GOOGLE_API_KEY')) # Corrected: using GOOGLE_API_KEY from environment

# Ensure embedding_model and collection are available from previous steps
# embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
# chroma_client = chromadb.Client()
# collection = chroma_client.get_or_create_collection(name="robotics_documentation")

def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with a supported model
    # Dynamically find a suitable model supporting 'generateContent'
    try:
        available_models = genai.list_models()
        # Prioritize 'gemini-pro' as it's typically the most capable and common
        supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods and 'gemini-pro' in m.name), None)
        if not supported_model_name:
            # Fallback to any other model that supports generateContent
            supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods), None)

        if not supported_model_name:
            raise ValueError("No generative model found that supports 'generateContent'.")

        model = genai.GenerativeModel(supported_model_name)
        print(f"Using LLM model: {supported_model_name}")

    except Exception as e:
        print(f"Error listing or selecting LLM model: {e}")
        # Fallback to a hardcoded model name if listing fails, or re-raise
        # For now, we'll use a placeholder error and let the generate_content catch it.
        model = None # Ensure model is None if selection fails

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.
    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.

    Retrieved Context:
    {context}

    User Query: {query}

    Answer:"""

    # 7. Generate a response from the LLM
    llm_response = "Error: LLM model not initialized properly." # Default error message
    if model:
        try:
            response = model.generate_content(prompt)
            llm_response = response.text
        except Exception as e:
            llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames

print("RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.")

RAG query function defined. Ready to use with a Google API Key and existing embedding model/ChromaDB collection.


/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning: 

All support for the `google.generativeai` package has ended. It will no longer be receiving 
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)


In [7]:
pip install chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.4/21.4 MB 80.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 22.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 64.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 83.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.0/220.0 kB 19.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.5 MB/s eta 0:00:00
  Attempting uninstall: opentelemetry-proto
    Fo

**Reasoning**:
The previous execution failed because `embedding_model` was not defined, and implicitly `collection` as well. I need to re-initialize the embedding model, ChromaDB client, and collection, and also redefine the `rag_query` function to ensure all these components are available in the current scope before running the evaluation.



In [4]:
import os
from google.colab import userdata
import google.generativeai as genai
from sentence_transformers import SentenceTransformer
import chromadb

# Re-initialize the embedding model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Embedding model 'all-MiniLM-L6-v2' re-initialized.")

# Re-initialize ChromaDB client and collection
chroma_client = chromadb.Client()
collection_name = "robotics_documentation"
collection = chroma_client.get_or_create_collection(name=collection_name)
print(f"ChromaDB collection '{collection_name}' re-accessed.")

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

# Re-define the rag_query function to ensure it's in scope and uses the re-initialized components
def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with a supported model
    try:
        available_models = genai.list_models()
        supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods and 'gemini-pro' in m.name), None)
        if not supported_model_name:
            supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods), None)

        if not supported_model_name:
            raise ValueError("No generative model found that supports 'generateContent'.")

        model = genai.GenerativeModel(supported_model_name)
        print(f"Using LLM model: {supported_model_name}")

    except Exception as e:
        print(f"Error listing or selecting LLM model: {e}")
        model = None # Ensure model is None if selection fails

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.\n    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.\n\n    Retrieved Context:\n    {context}\n\n    User Query: {query}\n\n    Answer:"""

    # 7. Generate a response from the LLM
    llm_response = "Error: LLM model not initialized properly." # Default error message
    if model:
        try:
            response = model.generate_content(prompt)
            llm_response = response.text
        except Exception as e:
            llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames


def evaluate_rag_system(dataset):
    """
    Evaluates the RAG system by processing each query in the dataset,
    retrieving a response, and storing the results.
    """
    evaluation_results = []
    for i, item in enumerate(dataset):
        query = item['query']
        reference_answer = item['reference_answer']

        print(f"\nProcessing evaluation query {i+1}/{len(dataset)}: {query}")

        generated_response = ""
        retrieved_sources = []
        try:
            generated_response, retrieved_sources = rag_query(query)
        except Exception as e:
            generated_response = f"Error during RAG query: {e}"
            print(f"Error processing query '{query}': {e}")

        evaluation_results.append({
            'query': query,
            'reference_answer': reference_answer,
            'generated_response': generated_response,
            'retrieved_sources': retrieved_sources
        })

    return evaluation_results

# Re-define evaluation_dataset here
evaluation_dataset = [
    {
        "query": "What are the two main operation modes of the OB-7000's gripper and when should each be used?",
        "reference_answer": "The OB-7000's gripper has two operation modes: Force-Controlled Mode, ideal for delicate objects, and Position-Controlled Mode, best for rigid objects requiring specific grip width."
    },
    {
        "query": "How often should the vision system be calibrated, and what are some best practices?",
        "reference_answer": "The vision system calibration should be performed weekly or after any mechanical adjustment. Best practices include calibrating in consistent lighting conditions and avoiding glare on the target."
    },
    {
        "query": "What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?",
        "reference_answer": "The maximum rated payload for the OB-7000 manipulator arm is 10 kg. For speeds exceeding 75% of max speed, the payload should be reduced by 20%."
    },
    {
        "query": "Describe the steps to restart the OB-7000 after an emergency stop.",
        "reference_answer": "To restart after an E-Stop: 1. Clear the hazard. 2. Twist the pressed E-Stop button clockwise to release it. 3. Reset the safety system on the teach pendant. 4. Initiate 'Power On' from the teach pendant or control panel."
    },
    {
        "query": "What are the physical dimensions and primary power requirements of the OmniBot 7000?",
        "reference_answer": "The OB-7000 has a footprint of 300 mm x 300 mm. Its primary power input is 200-240 VAC, single-phase, 50/60 Hz, and requires a 10 Amps dedicated circuit."
    },
    {
        "query": "What types of end-effectors are compatible with the OB-7000, and what electrical interface do they typically use?",
        "reference_answer": "The OB-7000 is compatible with standard grippers, welding torches, vision systems (e.g., EyeBot 3000 series), and force/torque sensors. The tool flange provides standard M8 connectors for electrical signals (24V DC, I/O)."
    },
    {
        "query": "What does error code E101 signify and what is the recommended action to resolve it?",
        "reference_answer": "Error code E101 signifies 'Joint Limit Exceeded'. This means the robot arm attempted to move beyond its physical joint limits. The recommended action is to check the program path, manually move the robot within limits using freedrive, and then reset the error."
    }
]

print("Starting RAG system evaluation...")
evaluation_results = evaluate_rag_system(evaluation_dataset)
print("Evaluation complete. Results stored in 'evaluation_results'.")

# Display a sample of the evaluation results
print("\nSample Evaluation Results (first 2 queries):")
for i, result in enumerate(evaluation_results[:2]):
    print(f"--- Query {i+1} ---")
    print(f"Query: {result['query']}")
    print(f"Reference Answer: {result['reference_answer']}")
    print(f"Generated Response: {result['generated_response']}")
    print(f"Retrieved Sources: {', '.join(result['retrieved_sources']) if result['retrieved_sources'] else 'None'}")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Embedding model 'all-MiniLM-L6-v2' re-initialized.
ChromaDB collection 'robotics_documentation' re-accessed.
Google API Key set from Colab secrets and genai re-configured.
Starting RAG system evaluation...

Processing evaluation query 1/7: What are the two main operation modes of the OB-7000's gripper and when should each be used?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 2/7: How often should the vision system be calibrated, and what are some best practices?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 3/7: What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 4/7: Describe the steps to restart the OB-7000 after an emergency stop.
Using LLM model: models/gemini-pro-latest



Processing evaluation query 5/7: What are the physical dimensions and primary power requirements of the OmniBot 7000?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 6/7: What types of end-effectors are compatible with the OB-7000, and what electrical interface do they typically use?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 7/7: What does error code E101 signify and what is the recommended action to resolve it?
Using LLM model: models/gemini-pro-latest


Evaluation complete. Results stored in 'evaluation_results'.

Sample Evaluation Results (first 2 queries):
--- Query 1 ---
Query: What are the two main operation modes of the OB-7000's gripper and when should each be used?
Reference Answer: The OB-7000's gripper has two operation modes: Force-Controlled Mode, ideal for delicate objects, and Position-Controlled Mode, best for rigid objects requiring specific grip width.
Generated Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for 

In [5]:
import os
from google.colab import userdata
import google.generativeai as genai
from sentence_transformers import SentenceTransformer
import chromadb

# Re-initialize the embedding model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Embedding model 'all-MiniLM-L6-v2' re-initialized.")

# Re-initialize ChromaDB client and collection
chroma_client = chromadb.Client()
collection_name = "robotics_documentation"
collection = chroma_client.get_or_create_collection(name=collection_name)
print(f"ChromaDB collection '{collection_name}' re-accessed.")

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

# Re-define the rag_query function to ensure it's in scope and uses the re-initialized components
def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with a supported model
    try:
        available_models = genai.list_models()
        supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods and 'gemini-pro' in m.name), None)
        if not supported_model_name:
            supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods), None)

        if not supported_model_name:
            raise ValueError("No generative model found that supports 'generateContent'.")

        model = genai.GenerativeModel(supported_model_name)
        print(f"Using LLM model: {supported_model_name}")

    except Exception as e:
        print(f"Error listing or selecting LLM model: {e}")
        model = None # Ensure model is None if selection fails

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.\n    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.\n\n    Retrieved Context:\n    {context}\n\n    User Query: {query}\n\n    Answer:"""

    # 7. Generate a response from the LLM
    llm_response = "Error: LLM model not initialized properly." # Default error message
    if model:
        try:
            response = model.generate_content(prompt)
            llm_response = response.text
        except Exception as e:
            llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames


def evaluate_rag_system(dataset):
    """
    Evaluates the RAG system by processing each query in the dataset,
    retrieving a response, and storing the results.
    """
    evaluation_results = []
    for i, item in enumerate(dataset):
        query = item['query']
        reference_answer = item['reference_answer']

        print(f"\nProcessing evaluation query {i+1}/{len(dataset)}: {query}")

        generated_response = ""
        retrieved_sources = []
        try:
            generated_response, retrieved_sources = rag_query(query)
        except Exception as e:
            generated_response = f"Error during RAG query: {e}"
            print(f"Error processing query '{query}': {e}")

        evaluation_results.append({
            'query': query,
            'reference_answer': reference_answer,
            'generated_response': generated_response,
            'retrieved_sources': retrieved_sources
        })

    return evaluation_results

# Re-define evaluation_dataset here
evaluation_dataset = [
    {
        "query": "What are the two main operation modes of the OB-7000's gripper and when should each be used?",
        "reference_answer": "The OB-7000's gripper has two operation modes: Force-Controlled Mode, ideal for delicate objects, and Position-Controlled Mode, best for rigid objects requiring specific grip width."
    },
    {
        "query": "How often should the vision system be calibrated, and what are some best practices?",
        "reference_answer": "The vision system calibration should be performed weekly or after any mechanical adjustment. Best practices include calibrating in consistent lighting conditions and avoiding glare on the target."
    },
    {
        "query": "What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?",
        "reference_answer": "The maximum rated payload for the OB-7000 manipulator arm is 10 kg. For speeds exceeding 75% of max speed, the payload should be reduced by 20%."
    },
    {
        "query": "Describe the steps to restart the OB-7000 after an emergency stop.",
        "reference_answer": "To restart after an E-Stop: 1. Clear the hazard. 2. Twist the pressed E-Stop button clockwise to release it. 3. Reset the safety system on the teach pendant. 4. Initiate 'Power On' from the teach pendant or control panel."
    },
    {
        "query": "What are the physical dimensions and primary power requirements of the OmniBot 7000?",
        "reference_answer": "The OB-7000 has a footprint of 300 mm x 300 mm. Its primary power input is 200-240 VAC, single-phase, 50/60 Hz, and requires a 10 Amps dedicated circuit."
    },
    {
        "query": "What types of end-effectors are compatible with the OB-7000, and what electrical interface do they typically use?",
        "reference_answer": "The OB-7000 is compatible with standard grippers, welding torches, vision systems (e.g., EyeBot 3000 series), and force/torque sensors. The tool flange provides standard M8 connectors for electrical signals (24V DC, I/O)."
    },
    {
        "query": "What does error code E101 signify and what is the recommended action to resolve it?",
        "reference_answer": "Error code E101 signifies 'Joint Limit Exceeded'. This means the robot arm attempted to move beyond its physical joint limits. The recommended action is to check the program path, manually move the robot within limits using freedrive, and then reset the error."
    }
]

print("Starting RAG system evaluation...")
evaluation_results = evaluate_rag_system(evaluation_dataset)
print("Evaluation complete. Results stored in 'evaluation_results'.")

# Display a sample of the evaluation results
print("\nSample Evaluation Results (first 2 queries):")
for i, result in enumerate(evaluation_results[:2]):
    print(f"--- Query {i+1} ---")
    print(f"Query: {result['query']}")
    print(f"Reference Answer: {result['reference_answer']}")
    print(f"Generated Response: {result['generated_response']}")
    print(f"Retrieved Sources: {', '.join(result['retrieved_sources']) if result['retrieved_sources'] else 'None'}")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Embedding model 'all-MiniLM-L6-v2' re-initialized.
ChromaDB collection 'robotics_documentation' re-accessed.
Google API Key set from Colab secrets and genai re-configured.
Starting RAG system evaluation...

Processing evaluation query 1/7: What are the two main operation modes of the OB-7000's gripper and when should each be used?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 2/7: How often should the vision system be calibrated, and what are some best practices?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 3/7: What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 4/7: Describe the steps to restart the OB-7000 after an emergency stop.
Using LLM model: models/gemini-pro-latest



Processing evaluation query 5/7: What are the physical dimensions and primary power requirements of the OmniBot 7000?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 6/7: What types of end-effectors are compatible with the OB-7000, and what electrical interface do they typically use?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 7/7: What does error code E101 signify and what is the recommended action to resolve it?
Using LLM model: models/gemini-pro-latest


Evaluation complete. Results stored in 'evaluation_results'.

Sample Evaluation Results (first 2 queries):
--- Query 1 ---
Query: What are the two main operation modes of the OB-7000's gripper and when should each be used?
Reference Answer: The OB-7000's gripper has two operation modes: Force-Controlled Mode, ideal for delicate objects, and Position-Controlled Mode, best for rigid objects requiring specific grip width.
Generated Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-3-pro
* Quota exce

**Reasoning**:
The previous execution failed with a `NameError: name 'evaluation_dataset' is not defined`. I need to ensure that `evaluation_dataset` is defined within the same code block before it is used by `evaluate_rag_system` to resolve this error.



In [6]:
import os
from google.colab import userdata
import google.generativeai as genai
from sentence_transformers import SentenceTransformer
import chromadb

# Re-initialize the embedding model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Embedding model 'all-MiniLM-L6-v2' re-initialized.")

# Re-initialize ChromaDB client and collection
chroma_client = chromadb.Client()
collection_name = "robotics_documentation"
collection = chroma_client.get_or_create_collection(name=collection_name)
print(f"ChromaDB collection '{collection_name}' re-accessed.")

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

# Re-define the rag_query function to ensure it's in scope and uses the re-initialized components
def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with a supported model
    try:
        available_models = genai.list_models()
        supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods and 'gemini-pro' in m.name), None)
        if not supported_model_name:
            supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods), None)

        if not supported_model_name:
            raise ValueError("No generative model found that supports 'generateContent'.")

        model = genai.GenerativeModel(supported_model_name)
        print(f"Using LLM model: {supported_model_name}")

    except Exception as e:
        print(f"Error listing or selecting LLM model: {e}")
        model = None # Ensure model is None if selection fails

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.\n    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.\n\n    Retrieved Context:\n    {context}\n\n    User Query: {query}\n\n    Answer:"""

    # 7. Generate a response from the LLM
    llm_response = "Error: LLM model not initialized properly." # Default error message
    if model:
        try:
            response = model.generate_content(prompt)
            llm_response = response.text
        except Exception as e:
            llm_response = f"Error generating LLM response: {e}"

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames


def evaluate_rag_system(dataset):
    """
    Evaluates the RAG system by processing each query in the dataset,
    retrieving a response, and storing the results.
    """
    evaluation_results = []
    for i, item in enumerate(dataset):
        query = item['query']
        reference_answer = item['reference_answer']

        print(f"\nProcessing evaluation query {i+1}/{len(dataset)}: {query}")

        generated_response = ""
        retrieved_sources = []
        try:
            generated_response, retrieved_sources = rag_query(query)
        except Exception as e:
            generated_response = f"Error during RAG query: {e}"
            print(f"Error processing query '{query}': {e}")

        evaluation_results.append({
            'query': query,
            'reference_answer': reference_answer,
            'generated_response': generated_response,
            'retrieved_sources': retrieved_sources
        })

    return evaluation_results

# Re-define evaluation_dataset here
evaluation_dataset = [
    {
        "query": "What are the two main operation modes of the OB-7000's gripper and when should each be used?",
        "reference_answer": "The OB-7000's gripper has two operation modes: Force-Controlled Mode, ideal for delicate objects, and Position-Controlled Mode, best for rigid objects requiring specific grip width."
    },
    {
        "query": "How often should the vision system be calibrated, and what are some best practices?",
        "reference_answer": "The vision system calibration should be performed weekly or after any mechanical adjustment. Best practices include calibrating in consistent lighting conditions and avoiding glare on the target."
    },
    {
        "query": "What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?",
        "reference_answer": "The maximum rated payload for the OB-7000 manipulator arm is 10 kg. For speeds exceeding 75% of max speed, the payload should be reduced by 20%."
    },
    {
        "query": "Describe the steps to restart the OB-7000 after an emergency stop.",
        "reference_answer": "To restart after an E-Stop: 1. Clear the hazard. 2. Twist the pressed E-Stop button clockwise to release it. 3. Reset the safety system on the teach pendant. 4. Initiate 'Power On' from the teach pendant or control panel."
    },
    {
        "query": "What are the physical dimensions and primary power requirements of the OmniBot 7000?",
        "reference_answer": "The OB-7000 has a footprint of 300 mm x 300 mm. Its primary power input is 200-240 VAC, single-phase, 50/60 Hz, and requires a 10 Amps dedicated circuit."
    },
    {
        "query": "What types of end-effectors are compatible with the OB-7000, and what electrical interface do they typically use?",
        "reference_answer": "The OB-7000 is compatible with standard grippers, welding torches, vision systems (e.g., EyeBot 3000 series), and force/torque sensors. The tool flange provides standard M8 connectors for electrical signals (24V DC, I/O)."
    },
    {
        "query": "What does error code E101 signify and what is the recommended action to resolve it?",
        "reference_answer": "Error code E101 signifies 'Joint Limit Exceeded'. This means the robot arm attempted to move beyond its physical joint limits. The recommended action is to check the program path, manually move the robot within limits using freedrive, and then reset the error."
    }
]

print("Starting RAG system evaluation...")
evaluation_results = evaluate_rag_system(evaluation_dataset)
print("Evaluation complete. Results stored in 'evaluation_results'.")

# Display a sample of the evaluation results
print("\nSample Evaluation Results (first 2 queries):")
for i, result in enumerate(evaluation_results[:2]):
    print(f"--- Query {i+1} ---")
    print(f"Query: {result['query']}")
    print(f"Reference Answer: {result['reference_answer']}")
    print(f"Generated Response: {result['generated_response']}")
    print(f"Retrieved Sources: {', '.join(result['retrieved_sources']) if result['retrieved_sources'] else 'None'}")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Embedding model 'all-MiniLM-L6-v2' re-initialized.
ChromaDB collection 'robotics_documentation' re-accessed.
Google API Key set from Colab secrets and genai re-configured.
Starting RAG system evaluation...

Processing evaluation query 1/7: What are the two main operation modes of the OB-7000's gripper and when should each be used?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 2/7: How often should the vision system be calibrated, and what are some best practices?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 3/7: What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 4/7: Describe the steps to restart the OB-7000 after an emergency stop.
Using LLM model: models/gemini-pro-latest



Processing evaluation query 5/7: What are the physical dimensions and primary power requirements of the OmniBot 7000?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 6/7: What types of end-effectors are compatible with the OB-7000, and what electrical interface do they typically use?
Using LLM model: models/gemini-pro-latest



Processing evaluation query 7/7: What does error code E101 signify and what is the recommended action to resolve it?
Using LLM model: models/gemini-pro-latest


Evaluation complete. Results stored in 'evaluation_results'.

Sample Evaluation Results (first 2 queries):
--- Query 1 ---
Query: What are the two main operation modes of the OB-7000's gripper and when should each be used?
Reference Answer: The OB-7000's gripper has two operation modes: Force-Controlled Mode, ideal for delicate objects, and Position-Controlled Mode, best for rigid objects requiring specific grip width.
Generated Response: Error generating LLM response: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-latest:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-3-pro
* Quota exceeded for 


**The previous code execution encountered repeated `429 Quota exceeded` errors from the Google Generative AI API, preventing the RAG system from fully generating responses for evaluation. To address this, the `rag_query` function needs to be updated to include a retry mechanism with exponential backoff when calling the LLM, to gracefully handle temporary API rate limits and improve the chances of successful response generation.**

I will now modify the `rag_query` function to incorporate `tenacity.retry` decorator to manage API quota issues more robustly. After redefining the `rag_query` function, I will re-run the evaluation process.

```python
import os
from google.colab import userdata
import google.generativeai as genai
from sentence_transformers import SentenceTransformer
import chromadb
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type
from google.api_core.exceptions import ResourceExhausted # Specific exception for quota issues

# Re-initialize the embedding model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Embedding model 'all-MiniLM-L6-v2' re-initialized.")

# Re-initialize ChromaDB client and collection
chroma_client = chromadb.Client()
collection_name = "robotics_documentation"
collection = chroma_client.get_or_create_collection(name=collection_name)
print(f"ChromaDB collection '{collection_name}' re-accessed.")

# Attempt to set the Google API Key from Colab secrets
try:
    api_key_value = userdata.get('GOOGLE_API_KEY')
    os.environ['GOOGLE_API_KEY'] = api_key_value
    genai.configure(api_key=api_key_value) # Reconfigure genai with the retrieved key
    print("Google API Key set from Colab secrets and genai re-configured.")
except userdata.SecretNotFoundError:
    print("WARNING: GOOGLE_API_KEY secret not found in Colab userdata. Please ensure it's added.")
    print("LLM functionality may be impaired as API key is not configured.")
    genai.configure(api_key=os.environ.get('GOOGLE_API_KEY'))

# Re-define the rag_query function to ensure it's in scope and uses the re-initialized components
# Add retry mechanism for LLM calls due to potential quota issues
@retry(
    stop=stop_after_attempt(5), # Try up to 5 times
    wait=wait_exponential(multiplier=1, min=4, max=60), # Wait 4s, 8s, 16s, 32s, 60s
    retry=retry_if_exception_type(ResourceExhausted), # Only retry on quota exceeded errors
    reraise=True # Re-raise the exception if all retries fail
)
def _generate_content_with_retry(model, prompt):
    return model.generate_content(prompt)

def rag_query(query: str, top_k: int = 3):
    """
    Retrieves relevant document chunks from the vector store based on a user query
    and generates a coherent response using an LLM.
    """
    # 1. Generate embedding for the input query
    query_embedding = embedding_model.encode([query]).tolist()[0]

    # 2. Use the query embedding to perform a similarity search on ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )

    retrieved_documents = results['documents'][0]
    retrieved_metadatas = results['metadatas'][0]

    # 3. Extract content of retrieved documents and format as context
    context = "\n\n".join([doc for doc in retrieved_documents])

    # 4. Prepare a list of unique source filenames
    source_filenames = sorted(list(set([m['source'] for m in retrieved_metadatas])))

    # 5. Initialize the generative model with a supported model
    model = None
    try:
        available_models = genai.list_models()
        supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods and 'gemini-pro' in m.name), None)
        if not supported_model_name:
            supported_model_name = next((m.name for m in available_models if 'generateContent' in m.supported_generation_methods), None)

        if not supported_model_name:
            raise ValueError("No generative model found that supports 'generateContent'.")

        model = genai.GenerativeModel(supported_model_name)
        print(f"Using LLM model: {supported_model_name}")

    except Exception as e:
        print(f"Error listing or selecting LLM model: {e}")
        model = None # Ensure model is None if selection fails

    # 6. Construct a detailed prompt for the LLM
    prompt = f"""You are an AI assistant for the OmniBot 7000 industrial robot.\n    Use the following retrieved context to answer the user's question. If the context does not contain the answer, state that you don't have enough information.\n\n    Retrieved Context:\n    {context}\n\n    User Query: {query}\n\n    Answer:"""

    # 7. Generate a response from the LLM with retry logic
    llm_response = "Error: LLM model not initialized properly or all retries failed." # Default error message
    if model:
        try:
            response = _generate_content_with_retry(model, prompt)
            llm_response = response.text
        except ResourceExhausted as re:
            llm_response = f"Error generating LLM response after multiple retries (Quota Exceeded): {re}"
            print(f"Final retry failed for query '{query}': {re}")
        except Exception as e:
            llm_response = f"Error generating LLM response: {e}"
            print(f"Error generating LLM response for query '{query}': {e}")

    # 8. Return the generated LLM response and the list of unique source filenames
    return llm_response, source_filenames


def evaluate_rag_system(dataset):
    """
    Evaluates the RAG system by processing each query in the dataset,
    retrieving a response, and storing the results.
    """
    evaluation_results = []
    for i, item in enumerate(dataset):
        query = item['query']
        reference_answer = item['reference_answer']

        print(f"\nProcessing evaluation query {i+1}/{len(dataset)}: {query}")

        generated_response = ""
        retrieved_sources = []
        try:
            generated_response, retrieved_sources = rag_query(query)
        except Exception as e:
            generated_response = f"Error during RAG query: {e}"
            print(f"Error processing query '{query}': {e}")

        evaluation_results.append({
            'query': query,
            'reference_answer': reference_answer,
            'generated_response': generated_response,
            'retrieved_sources': retrieved_sources
        })

    return evaluation_results

# Re-define evaluation_dataset here
evaluation_dataset = [
    {
        "query": "What are the two main operation modes of the OB-7000's gripper and when should each be used?",
        "reference_answer": "The OB-7000's gripper has two operation modes: Force-Controlled Mode, ideal for delicate objects, and Position-Controlled Mode, best for rigid objects requiring specific grip width."
    },
    {
        "query": "How often should the vision system be calibrated, and what are some best practices?",
        "reference_answer": "The vision system calibration should be performed weekly or after any mechanical adjustment. Best practices include calibrating in consistent lighting conditions and avoiding glare on the target."
    },
    {
        "query": "What is the maximum rated payload for the OB-7000, and how is it affected by high-speed operations?",
        "reference_answer": "The maximum rated payload for the OB-7000 manipulator arm is 10 kg. For speeds exceeding 75% of max speed, the payload should be reduced by 20%."
    },
    {
        "query": "Describe the steps to restart the OB-7000 after an emergency stop.",
        "reference_answer": "To restart after an E-Stop: 1. Clear the hazard. 2. Twist the pressed E-Stop button clockwise to release it. 3. Reset the safety system on the teach pendant. 4. Initiate 'Power On' from the teach pendant or control panel."
    },
    {
        "query": "What are the physical dimensions and primary power requirements of the OmniBot 7000?",
        "reference_answer": "The OB-7000 has a footprint of 300 mm x 300 mm. Its primary power input is 200-240 VAC, single-phase, 50/60 Hz, and requires a 10 Amps dedicated circuit."
    },
    {
        "query": "What types of end-effectors are compatible with the OB-7000, and what electrical interface do they typically use?",
        "reference_answer": "The OB-7000 is compatible with standard grippers, welding torches, vision systems (e.g., EyeBot 3000 series), and force/torque sensors. The tool flange provides standard M8 connectors for electrical signals (24V DC, I/O)."
    },
    {
        "query": "What does error code E101 signify and what is the recommended action to resolve it?",
        "reference_answer": "Error code E101 signifies 'Joint Limit Exceeded'. This means the robot arm attempted to move beyond its physical joint limits. The recommended action is to check the program path, manually move the robot within limits using freedrive, and then reset the error."
    }
]

print("Starting RAG system evaluation...")
evaluation_results = evaluate_rag_system(evaluation_dataset)
print("Evaluation complete. Results stored in 'evaluation_results'.")

# Display a sample of the evaluation results
print("\nSample Evaluation Results (first 2 queries):")
for i, result in enumerate(evaluation_results[:2]):
    print(f"--- Query {i+1} ---")
    print(f"Query: {result['query']}")
    print(f"Reference Answer: {result['reference_answer']}")
    print(f"Generated Response: {result['generated_response']}")
    print(f"Retrieved Sources: {', '.join(result['retrieved_sources']) if result['retrieved_sources'] else 'None'}")
```